version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: twittergram_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: twittergram
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: twittergram_redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
